services:
  - type: web
    name: hoc-cung-con
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run src/app.py --server.port $PORT --server.address 0.0.0.0
    autoDeploy: false
